### ISSUE TITLE
Old application insights api is used

### ISSUE THREAD

**Issue by KiselN** [MarkPieszak/angular-application-insights#1]
I am pretty sure that `logEvent` and `start` methods are from the old library. The new API is described here https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md

**Comment by MarkPieszak** [comment]
Oh thank you @KiselN !
My apologies, I was just getting things setup, must of been looking at some old/wrong documentation!

**Comment by KiselN** [comment]
No problem @MarkPieszak 
I've been trying some things today for my project. Can make a PR soon with new api and basic page tracking implementation.

**Comment by MarkPieszak** [comment]
I just updated and added a few of the APIs (none of them implemented yet), if you want to take a look and make any neccessary PRs! 

Started going down that list adding everything and copying the signatures so far.  Stopped right before adding `Config()`

Really appreciate it! :+1:

**Comment by MarkPieszak** [comment]
One problem I'm realizing now is that if we use the SDK it probably isn't built in a Universal fashion, where it's making sure `window` even exists. I'll have to look into it.

**Comment by viperguynaz** [comment]
@MarkPieszak - latest client-side API implemented in rc.0 - for Universal though I'd recommend using the [Node.js SDK](https://www.npmjs.com/package/applicationinsights).

📕 I'd recommend closing this issue.

**Comment by MarkPieszak** [comment]
Thank you @viperguynaz ! 💯 🥅 ⚽️
