### ISSUE TITLE
forRoot() with observable

### ISSUE THREAD

**Issue by deKaantje** [MarkPieszak/angular-application-insights#13]
Hi Mark,

First of all; Love the package, easy setup and use! 

My 'issue' is as follows:

I want to load configuration settings that contain the instrumentation key. This instrumentation key is therefore not directly known when the app.module is executed. So calling the _forRoot()_ with the key is not an option. 

Would it be possible to use an observable (preferred) or promise to set the key? I could then use the Route Resolver or the APP_INITIALIZER to retrieve the configuration settings. When the key becomes available it could set it in the _ApplicationInsightsModule_.

If you have a working alternative for my problem, I would love to know your solution!

Thanks in advance,

Stephan Kaneman

**Comment by MarkPieszak** [comment]
@deKaantje thank you for the kind words! Glad it's helping people out there 👍

So you have a few options (some better, some worse), but unfortunately at least by their current design you can't have a forRoot or anything at that low of a level be Async (since it's at the lowest NgModule level). 

The easiest way to achieve this would be to get this apiKey on the server (before anything even gets rendered) and pass it down either in a script tag, on the `window` object, and pluck it from here when doing useFactory to get the AppInsightsModule and creating your forRoot.

Hope that helps clear it up a little bit ?

**Comment by deKaantje** [comment]
@MarkPieszak Thank you for the response. I had thought about that solution, but it places the config retrieval outside of my Angular environment. It feels a bit dirty to me; kind of last resort. 
I will have to do some more digging / thinking! 

I will get back on this if I find a solution. Thank you for your time!

**Comment by MarkPieszak** [comment]
The other option is doing the call before bootstrap, and then once you have it, bootstrap the application and then you can pass in that appId.

The window TransferData is a very common way to pass down server data to HTML, but it does seem strange at first no doubt !

Hope that helps get you in the right direction!

I'll try to talk to the team. Let me know how you end up.

**Comment by MarkPieszak** [comment]
@deKaantje Hope you figured it out eventually?

I'd imagine APP_INITIALIZER would be the best way to go about it, as the app won't start up until that Promise is finished.

For example something like...

    {
      provide: APP_INITIALIZER,
      useFactory: (config: ConfigurationService) => () => config.getConfig(),
      deps: [ConfigurationService],
      multi: true
    },

Set whatever you need on some kind of public or static property within that ConfigurationService, and you should be able to access it later wherever you need.

**Comment by deKaantje** [comment]
@MarkPieszak  We currently solved it by putting a config object on the window object. Not my preferable solution, but for now it works. 

We'll keep it on the backlog, so we'll look into it a bit later..

Thank you for the help!

**Comment by jandresampaio** [comment]
Using the AppInitializer still would not be possible the key in the forRoot method, inside AppModule. So how would we set the key afterwards ?
