### ISSUE TITLE
Ability to override startTrackPage name and stopTrackPage name

### ISSUE THREAD

**Issue by pderks** [MarkPieszak/angular-application-insights#14]
Within the _init()_ function of _app-insight.service.ts_ startTrackPage() and stopTrackPage() gets called for me with the name specified as event.url. It would be nice to be able to provide a custom name of my choosing for page view events.

**Proposed Solution:** 
Enable the ability to set a flag to disable this functionality, so that I can create my own implementation without having duplicate page views show up in app insights.

**Comment by MarkPieszak** [comment]
Good idea! We can definitely add something like this in there to make it more customizable. 👍
