### ISSUE TITLE
Karma Tests with angular-application-insights

### ISSUE THREAD

**Issue by MrTimms** [MarkPieszak/angular-application-insights#16]
Hi @MarkPieszak. I'm trying to write karma tests for my app. I'm pretty new to karma so this probably a problem with me and not your package. But when I run my tests I get an error that says:

     Error: No provider for AppInsightsService!

Do you know how to fix this? Or do you know of any other projects that run karma tests with your package so I can see how they fix this problem?

Thanks!

**Comment by MarkPieszak** [comment]
Did you add it in the Providers list for your TestBed?

**Comment by MrTimms** [comment]
Thanks for the advice. 
I'll try stubbing it out.
