### ISSUE TITLE
Unmet peer dependency

### ISSUE THREAD

**Issue by jessenic** [MarkPieszak/angular-application-insights#21]
The new version (2.2.0) breaks my npm dependencies. It depends on 4.1.1 angular packages while it probably should depend on all 4.x packages. I'm running Angular 4.2.5. Version 2.0.0 works fine so I'm using it until this gets fixed.

**Comment by MarkPieszak** [comment]
Just fixed it, apologies! Thanks for letting me know.
`2.3.0 released to npm` 🍾 

@jessenic
