### ISSUE TITLE
An instrumentationKey value is required to initialize AppInsightsService 

### ISSUE THREAD

**Issue by isaac2004** [MarkPieszak/angular-application-insights#22]
I am using this in conjunction with [this](https://github.com/MarkPieszak/aspnetcore-angular2-universal) and I am getting above error on App Load in console. I assume this is order of operations issue since the key is injected into the service at some point (Api calls to AppInsights are successful). Here is what I am doing in main.server.ts (as well as aot)

````
  return ngAspnetCoreEngine(setupOptions).then(response => {
    // Apply your transferData to response.globals
    response.globals.transferData = createTransferScript({
        AppInsightsId: 'Key'
    });
````
and in browser-app.module

````
  ApplicationInsightsModule.forRoot({
            instrumentationKey: window['TRANSFER_CACHE']['AppInsightsId']
        }),

````

The key is on the window object, yet I get this error when the site loads. I have 2 questions.

1. When do I inject the key into the service to make that warning go away
2. I am currently storing it in the main.server.ts, but I want to supply it from Server side. what would that look like? I am already putting it on TransferData in HomeController, but this line

````
AppInsightsId2: params.data.AppInsightsId
````
Never gets populated.

**Comment by MarkPieszak** [comment]
Assume we have this one fixed as you figured out the rendering! Cheers.

**Comment by isaac2004** [comment]
I am still having a loading issue where the service isn't loading the key. See that 343 in the other repo

**Comment by isaac2004** [comment]
@MarkPieszak you can close this and we can just chat in the other one. Sorry to cross streams here
