### ISSUE TITLE
overrideTrackPageMetrics not included in typings file

### ISSUE THREAD

**Issue by pderks** [MarkPieszak/angular-application-insights#23]
The overrideTrackPageMetrics property in the AppInsightsConfig is not being included in the app-insight.service.d.ts typings file in the dist folder. Running npm run build on a local branch of the code seems to generate the typings file with this property. However, when doing an npm install overrideTrackPageMetrics does not appear in the typings file.

Previously this was not an issue in version 2.2.0, but since the release of version 2.3.0 this doesn't work in either version (2.2.0 and 2.3.0).

**Comment by MarkPieszak** [comment]
Thanks for logging this! Haven't seen that, I'm wondering if somehow it didn't publish properly that's strange, if it's building locally it definitely should be there hmm. I'll take a look!

**Comment by pderks** [comment]
@MarkPieszak Thanks!

**Comment by pderks** [comment]
Is there any update on this?

**Comment by MarkPieszak** [comment]
Sorry about that delay! Finally had a second to look, it's been updated to 2.3.1, get latest and you should see it in there. Apologies about the delay :(

**Comment by pderks** [comment]
No worries. Thank you!
