### ISSUE TITLE
Initialize instrumentationKey via http request

### ISSUE THREAD

**Issue by svNet** [MarkPieszak/angular-application-insights#24]
Hi.
I have multiple application insight instances, which correspond to my runtime environments (DEV, ACT, PROD). I am searching for the best way to set up the instrumentationKey dependent on the environment it was distributed from. I was thinking about requesting the corresponding server, if this is possible in any way.
Do you know how I could achieve this the best?

**Comment by MarkPieszak** [comment]
Currently APP_INITIALIZER would be the best way, where you'd make the request and then when the app actually bootstraps you already have the string ready. 

I'm working on better ways of handling the key, like from an http observable so this can be easier in the future and then fire off the other events when it's all ready. For now use the initializer though! Cheers.

**Comment by MarkPieszak** [comment]
fixed via  2c6c713 thanks to @jycouet
