### ISSUE TITLE
Release 2.3.3 breaks build

### ISSUE THREAD

**Issue by janvanuytrecht** [MarkPieszak/angular-application-insights#28]
Moving the typings dependency from dev to peer forces people using the package to include the typings package to their dev dependency package list.

Maybe this is as intended, but then it should be included in the readme I guess.

**Comment by mikemwalsh** [comment]
Confirmed.  2.3.3 is coming down on NPM for me now on my build server (using ^2.0.0 in package.json) and the build is broken.  Minor/build version releases should not cause breaking changes.  I have locked myself at 2.3.2 for now.

**Comment by MarkPieszak** [comment]
It seemed we needed it for another precious issue, do we need to put it back to where it was? @mikemwalsh @janvanuytrecht Apologies guys!

**Comment by janvanuytrecht** [comment]
No worries. 

I would just note it in the readme file that consumers should also include the typings in their Dev dependencies. And add it as a dependency on the npm site



Mvg,
Jan.

**Comment by mikemwalsh** [comment]
@MarkPieszak I am actually not sure this specifically was my issue.  I had to roll back to a previous version.  I will try to figure out what broke it for me and report back

**Comment by MarkPieszak** [comment]
Should be fixed now via `2.3.4`, just tested on a blank angular-cli project and no errors when building or installing :) @mikemwalsh @janvanuytrecht 

Sorry about that!
