### ISSUE TITLE
How to unit test a component that uses this service?

### ISSUE THREAD

**Issue by EthanMelamed** [MarkPieszak/angular-application-insights#32]
Hi,

I have a component that bring in the service in the constructor like this:

constructor(
            public appInsights: AppInsightsService, ...
){ ... }

How do I then set up my spec file?

Thanks,
Ethan

**Comment by MarkPieszak** [comment]
Hey Ethan,

As these are outside of the component itself, I'd simply `mock` the AppInsightsService with some blank/noop() functions, just focus on the core functionality of your component itself.

You could just mock it like:

```ts
const AppInsightsService = {
  trackEvent: () => { }, 
  // etc etc
}
```
