### ISSUE TITLE
NodeInvocationException: StaticInjectorError[AppInsightsService]: 

### ISSUE THREAD

**Issue by Farre82** [MarkPieszak/angular-application-insights#33]
Hi,
When switching from 
<app asp-ng2-prerender-module="ClientApp/dist/main-server">Loading...</app> 
to
<app asp-prerender-module="ClientApp/dist/main-server">Loading...</app>
I am getting NodeInvocationException: StaticInjectorError[AppInsightsService].

I use JavascriptServices with Angular 5 and .Net Core 2.0
Please Help!

**Comment by MarkPieszak** [comment]
Are you doing Universal / Server-side rendering?
If so you have to set it up a little bit differently: https://github.com/MarkPieszak/angular-application-insights#usage-with-aspnetcore-angular2-universal-repo-or-javascriptservices--apps-w-server-side-rendering-

**Comment by Farre82** [comment]
You are right, I'm using Serverside rendering, thanks!

Another question on setting context properties like version, UserID. Is that possible?
