### ISSUE TITLE
Support Angular 5

### ISSUE THREAD

**Issue by dfederm** [MarkPieszak/angular-application-insights#34]
Angular 5 has been out now for a little while, so it'd be nice to add support for it.

At a glance at least in my app, it just works as-is. I'm just getting this error with `npm install`:

```
npm WARN @markpieszak/ng-application-insights@2.4.2 requires a peer of @angular/router@^4.0.0 but none is installed. You must install peer dependencies yourself.
```

So optimistically, only the `package.json` needs to be updated and it'll just work.

**Comment by MarkPieszak** [comment]
Thank you @dfederm !

Fixed via https://github.com/MarkPieszak/angular-application-insights/commit/60f04b9c58be28fd86a6676bcbfb477ac575e21f

Apologies on the delay.
