### ISSUE TITLE
Rxjs Pipeable operators

### ISSUE THREAD

**Issue by LanceEa** [MarkPieszak/angular-application-insights#35]
I have started seeing the following screen shot.

<img width="867" alt="screen shot 2018-02-06 at 2 00 54 pm" src="https://user-images.githubusercontent.com/8103374/35881435-6153400c-0b46-11e8-9a9d-e03a9d09a4d3.png">

Looking at the code in Chrome Dev Tools it looks like the `rxjs/add/operator/filter` is not getting added to my bundle which means that `filter` is not available on the `this.router.events` subject.

I have a PR to follow that will update the rxjs dependency to `^5.5.5` and switches to using the pipeable version of filter. 

** Note ** - I'm using Angular & Angular-cli master so I didn't dig too deep on why this started popping up but that could be the reason why it is no longer added to Observable prototype. I'm also completely using pipeable operators throughout my app so I'm guessing the bundle excludes the add operators code.

**Comment by MarkPieszak** [comment]
fixed via 3321782 

Thank you @LanceEa !
Merged & published 4.0.0 :+1:

**Comment by LanceEa** [comment]
no problem! Thanks for getting it merged and published! 👍
