### ISSUE TITLE
setAuthenticatedUserContext doesn't follow the application insights contract

### ISSUE THREAD

**Issue by dloukola** [MarkPieszak/angular-application-insights#41]
setAuthenticatedUserContext doesn't allow the ability to use the storeInCookie param.

https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md#setauthenticatedusercontext

**Comment by dloukola** [comment]
I'll fix this, if I'm allowed to create a pull request.

**Comment by MarkPieszak** [comment]
Of course! I didn't know we were missing that functionality, so sorry about that!
Let me know, I'll take a look and get the PR merged & published as soon as I can. @dloukola 
💯

**Comment by GustavoAmerico** [comment]
I have the same problem, discover it needs call setAuthenticatedUserContext before trackEvent 
I'm investigating how to solve in page change.

**Comment by MarkPieszak** [comment]
Fix published just now! Thank you :+1: @GustavoAmerico 
@dloukola
