### ISSUE TITLE
Package "@markpieszak/ng-application-insights" has an incompatible peer dependency to "rxjs" (requires "^5.5.5", would install "6.1.0")

### ISSUE THREAD

**Issue by jycouet** [MarkPieszak/angular-application-insights#43]
Hello, 

I'm trying to update my application to Angular6, but I have an issue.
Here is what I get when I do a :`ng update @angular/core`

`Package "@markpieszak/ng-application-insights" has an incompatible peer dependency to "rxjs" (requires "^5.5.5", would install "6.1.0").`

Could you have a look?
Let me know if you need help :)

**Comment by kealin** [comment]
Yes please, I seem to get this error from a similar setup with rxjs 6.0.0:

ERROR in ./node_modules/@markpieszak/ng-application-insights/dist/src/app-insight.service.js
Module not found: Error: Can't resolve 'rxjs/operators/filter' in 'C:\**\node_modules\@markpieszak\ng-application-insights\dist\src'

**Comment by jycouet** [comment]
Actually, just updating rxjs to `6.1.0` (and peer) and changing the import from `rxjs/operators/filter` to `rxjs/operators` should work :)

**Comment by MarkPieszak** [comment]
I think you're right @jycouet 👍 
Just published ng-application-insights 5.0 - let me know if that works for you guys!
