### ISSUE TITLE
trackTrace API does not support setting severity level

### ISSUE THREAD

**Issue by GFoley83** [MarkPieszak/angular-application-insights#44]
The API for trackTrace:
https://github.com/MarkPieszak/angular-application-insights/blob/master/src/app-insight.service.ts#L145

needs to be extended to support setting the severity level e.g. info, warn, etc.

As can be seen here:

https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md#tracktrace

**Comment by MarkPieszak** [comment]
Fixed via 
https://github.com/MarkPieszak/angular-application-insights/commit/55a453c59539277d976b02404d8fae4fec14d374

Thanks for finding this one! :+1: :100:

**Comment by GFoley83** [comment]
Cheers for the quick turnaround @MarkPieszak. Is there any chance of getting this for version 4 as well?
