### ISSUE TITLE
Dependency on @angular/router breaks compatibility with Ionic

### ISSUE THREAD

**Issue by GFoley83** [MarkPieszak/angular-application-insights#45]
We're currently trying to use `angular-application-insights` across our various Angular applications, one of which is built in Ionic. Given the current version of Ionic (v.3) does not use `@angular/router`, we are getting the same error mentioned in Issue #25 `Unhandled Promise rejection: No provider for Router!`, which is due to the hard dependency on Angular Router inside `AppInsightsService`.

**Comment by GFoley83** [comment]
I'm not sure but I don't think using `@Optional` will work here and you'd still be importing `@angular/router`, which is what will throw the error as it won't be installed.

**Comment by MarkPieszak** [comment]
Yeah I think we might need to omit it entirely and warn people that they need to add that code themselves if they want it to handle those events, let me test a few things out.

**Comment by fakerLinXiao** [comment]
@MarkPieszak   Hello. I use ionic too. The error is  "No module for @angular/router". How to resolve it? 
"@angular/core": "4.1.2"
"@markpieszak/ng-application-insights": "^2.4.2"

**Comment by MarkPieszak** [comment]
Fixed with the latest version 5.0.4 @GFoley83 
We're grabbing the Router via the Injector now, so it shouldn't have any issues now!
Sorry about the delay there.

Closing out but please open up if it still didn't fix it!
