### ISSUE TITLE
StringValueTooLong message:"string value is too long.

### ISSUE THREAD

**Issue by SandyVeliz** [MarkPieszak/angular-application-insights#49]
Hi! i m making an App with AD B2C and yours Git for AI, and every time the app get the AccesToken throw this warning:

AI: StringValueTooLong message:"string value is too long. It has been truncated to 1024 characters." props:"

![image](https://user-images.githubusercontent.com/29709496/42345420-acb361b8-8075-11e8-8417-38156aaeca30.png)

At first, I thought it was the problem of the Application-Js repository, so I asked them:[https://github.com/Microsoft/ApplicationInsights-JS/issues/174](url)

But they replied that the latest version (1.0.16) has already solved that problem, and they saw that in their repository they are using as dependency a previous version (1.0.15).
[https://github.com/Microsoft/ApplicationInsights-JS/issues/566](url)

There is a way to make this fix local until the new version comes?

**Comment by MarkPieszak** [comment]
Closing out but let me know if the latest 5.0.4 doesn't fix this either - feel free to open a new issue!

**Comment by Gobbenobber** [comment]
Still getting this with 6.0.1 and even 7.0.1!
