### ISSUE TITLE
NavigationCancel/NavigationError events do not call stopTrackPage

### ISSUE THREAD

**Issue by alisd23** [MarkPieszak/angular-application-insights#50]
Currently, the service **starts** tracking a page on a `NavigationStart` event, and **stops** tracking a page on `NavigationEnd only`.

The service should also stop tracking a page on the following events:
- `NavigationCancel`: An event triggered when navigation is canceled. This is due to a Route Guard returning false during navigation.
- `NavigationError`: An event triggered when navigation fails due to an unexpected error.

Link for Angular routing events: https://angular.io/guide/router#router-events

**Comment by MarkPieszak** [comment]
Fixed via https://github.com/MarkPieszak/angular-application-insights/commit/d96451c0cd4a2b3fc1809a51c9340b8b21112266

Thank you again @alisd23 🍻🍻🍻
