### ISSUE TITLE
TypeError when running ng serve in production mode

### ISSUE THREAD

**Issue by maxm-se** [MarkPieszak/angular-application-insights#63]
Hi,

I have an issue since version 5.0.4 when building my application with --prod option (ng serve --prod).

```javascript
Angular application insights Error [downloadAndSetup]:  TypeError: this._injector.get is not a function
    at e.get [as router] (main.b0d98d02747b3ebe4744.js:1)
    at e.init (main.b0d98d02747b3ebe4744.js:1)
    at new <anonymous> (main.b0d98d02747b3ebe4744.js:1)
    at wa (main.b0d98d02747b3ebe4744.js:1)
    at ya (main.b0d98d02747b3ebe4744.js:1)
    at Za (main.b0d98d02747b3ebe4744.js:1)
    at Wa (main.b0d98d02747b3ebe4744.js:1)
    at Object.ps [as createRootView] (main.b0d98d02747b3ebe4744.js:1)
    at t.create (main.b0d98d02747b3ebe4744.js:1)
    at t.create (main.b0d98d02747b3ebe4744.js:1)
```

When building my app in dev mode, everything is ok. I think that the issue is due to this change https://github.com/MarkPieszak/angular-application-insights/commit/ee3df015119ecc53704a9dc5162e2924f4a211e3. I investigated a bit and when the app is build in production mode, the parameters in the AppInsightsService are not what we are expecting. _injector is the Router.

I tried to investigate more but with no significant results. I will probably rollback to 5.0.3 but if have a fix to provide, it would be nice :)

I'm using dev deps:
```
    "@angular/compiler-cli": "6.1.10",
    "@angular/cli": "6.2.6",
```
and deps:
```
"@angular/animations": "6.1.10",
    "@angular/cdk": "6.4.7",
    "@angular/common": "6.1.10",
    "@angular/compiler": "6.1.10",
    "@angular/core": "6.1.10",
    "@angular/flex-layout": "6.0.0-beta.18",
    "@angular/forms": "6.1.10",
    "@angular/material": "6.4.7",
    "@angular/material-moment-adapter": "6.4.7",
    "@angular/platform-browser": "6.1.10",
    "@angular/platform-browser-dynamic": "6.1.10",
    "@angular/router": "6.1.10",
```

Thank you

**Comment by MarkPieszak** [comment]
Hey @maxm-se 
We're all set now with version **`6.0.3`** published to npm. There's also a 7.0.0 version released to prevent an npm warning for Angular 7+.

It was because I didn't have a try/catch around it for when Router isn't available, in the case of people using UIRouter!

You're all set now 🎁

**Comment by MarkPieszak** [comment]
Closing as fixed via https://github.com/MarkPieszak/angular-application-insights/commit/d2443f1f663aebe429d00a7ca6b8cab791236377
