### ISSUE TITLE
npm dependency warning

### ISSUE THREAD

**Issue by wmgdev** [MarkPieszak/angular-application-insights#64]
I've just upgraded to angular 7.0.4 and 6.0.1 and got this npm warning. I have this in my package file

`"@markpieszak/ng-application-insights": "^6.0.1"`
`"@angular/router": "^7.0.4"`,

this is the warning

`npm WARN @markpieszak/ng-application-insights@6.0.1 requires a peer of @angular/router@^6.0.0 but none is installed. You must install peer dependencies yourself. `

**Comment by MarkPieszak** [comment]
Let me create a new version to match with 7.x! Sorry about the delay

**Comment by MarkPieszak** [comment]
Fixed via releasing @markpieszak/ng-application-insights **`7.0.0 `**

Hope that helps! Thanks for the heads up 👍
