### ISSUE TITLE
Compilation error in ng2 app: Calling function 'ApplicationInsightsModule', function calls are not supported

### ISSUE THREAD

**Issue by aguerot** [MarkPieszak/angular-application-insights#7]
Hi,

I am facing a compilation issue today. he exact same code was compiling fine last week.
Here is the offending line in my app.module.ts as per the TS compiler:
`
 import { ApplicationInsightsModule } from '@markpieszak/ng-application-insights';
 ...
 imports: [
    ...
    ApplicationInsightsModule.forRoot({
      appID: <myid>,
      appName: <myproj>
    })
  ],`

Here is the compiler error:
`ERROR in Error encountered resolving symbol values statically. Calling function 'ApplicationInsightsModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function`

Is there a new way to initialize the AppInsights module?
I am running off 1.0.0-rc.0 version.

Update: I am using Angular CLI 1.0.0-rc.2 to compile

Rgds

**Comment by MarkPieszak** [comment]
That's my fault in that I'm not AoTing the library to package the metadata.json files that are neccessary on your end (since you're trying to AoT your application).

I'll have to fix that and republish a new version, apologies!

**Comment by MarkPieszak** [comment]
Just published an update to the library to fix up the library so that it publishes AoT metadata files.
Can you give it a shot?

The latest is now 1.0.0-rc.1 it also includes some great updates from Don @viperguynaz ! (You can see those updates [here](https://github.com/MarkPieszak/angular-application-insights/pull/6))
@markpieszak/ng-application-insights@1.0.0-rc.1

**Comment by aguerot** [comment]
I've updated to 1.0.0-rc.1. Works like a charm!
Thanks for getting this fixed that quickly, really appreciate.
@viperguynaz, your updates are really nice as well
Keep up the good work guys

**Comment by MarkPieszak** [comment]
glad to hear it's working ! 
Are you getting all the necessary data stored in Azure as well?

Love to see some screenshots of it in action with your app 😀

**Comment by aguerot** [comment]
![image](https://cloud.githubusercontent.com/assets/11557948/24454836/b23a6a3c-148d-11e7-9a8c-56a71ddef989.png)
I've only setup trackpage and trackevent with custom data but I can find all my telemetry up in Azure

**Comment by MarkPieszak** [comment]
That's great!! :)
