### ISSUE TITLE
Example with webpack integration

### ISSUE THREAD

**Issue by auhorn** [MarkPieszak/angular-application-insights#8]
Hi

I tried to include this library in an asp.net core Angular JavascriptServices application and have the hardest time to get it up and running. Do you have an example how it does need to be configured?  I installed the package and change my root module but I am not sure what else needs to be done. 

Thank you in advance!
Torsten

**Comment by auhorn** [comment]
Needed to add `"@types/applicationinsights-js":` to the `devDependencies` in the package.json.

**Comment by MarkPieszak** [comment]
Ahh would it help if we add it to the dependencies here? Or should we make note of it in the Readme?

**Comment by auhorn** [comment]
I would add this as a dependency to have it "working out of the box" but Readme would do it as well.  THANK YOU!

**Comment by MarkPieszak** [comment]
Yeah let me just add it as a dependency, thanks for pointing it out!
