### ISSUE TITLE
Cannot find namespace 'Microsoft'.

### ISSUE THREAD

**Issue by MrTimms** [MarkPieszak/angular-application-insights#9]
Thanks for your hard work!

I've hit a compilation error and I don't know how to solve it. Can you take a look at this for me?
I'm using Angular 4.0.1, Angular-CLI 1.0.0, and your module @markpieszak/ng-application-insights 1.0.0-rc.1

Please let me know if you need more information.

    ERROR in c:/master/node_modules/@markpieszak/ng-application-insights/dist/src/app-insight.service.d.ts (4,23): Cannot find namespace 'Microsoft'.
    c:/master/node_modules/@markpieszak/ng-application-insights/dist/src/app-insight.service.d.ts (5,51): Cannot find namespace 'Microsoft'.
    c:/master/node_modules/@markpieszak/ng-application-insights/dist/src/app-insight.service.d.ts (37,14): Cannot find namespace 'Microsoft'.
    c:/master/node_modules/@markpieszak/ng-application-insights/dist/src/app-insight.service.d.ts (39,13): Cannot find namespace 'Microsoft'.
    c:/master/node_modules/@markpieszak/ng-application-insights/dist/src/app-insight.service.d.ts (70,24): Cannot find namespace 'AI'.
    c:/master/node_modules/@markpieszak/ng-application-insights/dist/src/app-insight.service.d.ts (1,1): Cannot find type definition file for 'applicationinsights-js'.

Here is the relevant part of my app.module file:

    import { ApplicationInsightsModule, AppInsightsService } from '@markpieszak/ng-application-insights';
    @NgModule({
      imports: [
        ...
        ApplicationInsightsModule.forRoot({ instrumentationKey: 'My-Key' })
      ],
       ...

      providers: [
         ...
        AppInsightsService,
       ...
      ]

Here is the relevant part of my component:

    import { AppInsightsService } from '@markpieszak/ng-application-insights';
    ...
    
    constructor(
       ...
       private appInsightsService: AppInsightsService) {}
    
    ...
    doSomething() {
         this.appInsightsService.trackPageView('WelcomePage')
    }

**Comment by aguerot** [comment]
I am having the exact same issue when trying to upgrade my app to ng4

**Comment by hakonamatata** [comment]
Also experiencing the same problem

**Comment by MarkPieszak** [comment]
Does adding "@types/applicationinsights-js":` to the `devDependencies` in the package.json help fix this one? I be,I've I need to add it to the dependencies of the library here!

**Comment by aguerot** [comment]
Adding `@types/applicationinsights-js` to the devDependencies does the trick indeed. I haven't tried to add to your library though.  Only to my ng4 app.

**Comment by MarkPieszak** [comment]
Yeah I think that'll handle it, let me add it in the project and push a new version to `npm`!

**Comment by MarkPieszak** [comment]
Published 1.0.0, let me know if there's still any problems 👍 
@aguerot @hakonamatata @MrTimms

**Comment by MrTimms** [comment]
@MarkPieszak I no longer see this compile time error. I am seeing a couple of compile time warnings and a run time error when I do an --aot build. I'll start a new thread for that issue.
